# Generated by Django 6.0.5 on 2026-05-07 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_slug', models.SlugField(max_length=80)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organisationsanfrage',
                'verbose_name_plural': 'Organisationsanfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#0F766E', max_length=7, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige HEX-Farbe verwenden, z. B. #0F766E.', regex='^#([A-Fa-f0-9]{6})$')])),
                ('secondary_color', models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige HEX-Farbe verwenden, z. B. #0F766E.', regex='^#([A-Fa-f0-9]{6})$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_logos', to='media_assets.imageasset')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'ordering': ['name'],
            },
        ),
    ]
