# Generated by Django 6.0.5 on 2026-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_admin', 'Organisations-Admin'), ('staff', 'Mitarbeiter/in'), ('inspector', 'Kontrolleur/in'), ('manager', 'Fachverantwortliche/r')], max_length=30)),
                ('is_active_for_organization', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
