# Generated by Django 6.0.5 on 2026-05-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_inspect',
            field=models.BooleanField(default=False, help_text='Darf Kontrollen starten, Prüfantworten erfassen und Kontrollen abschliessen.', verbose_name='Kontrollen durchführen'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_maintain',
            field=models.BooleanField(default=False, help_text='Darf Mängel und Instandhaltungsmassnahmen erfassen und bearbeiten.', verbose_name='Mängel und Unterhalt bearbeiten'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_internal',
            field=models.BooleanField(default=True, help_text='Darf interne Daten der eigenen Organisation ansehen.', verbose_name='Interne Ansicht'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='Darf Stammdaten und Einstellungen der eigenen Organisation verwalten.', verbose_name='Organisationsverwaltung'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active_for_organization',
            field=models.BooleanField(default=True, verbose_name='Aktiv für Organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='tenants.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
