# Generated by Django 6.0.5 on 2026-05-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0002_initial'),
        ('playgrounds', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_description', models.TextField()),
                ('internal_note', models.TextField(blank=True)),
                ('has_safety_risk', models.BooleanField(default=False, help_text='Ja, wenn der Mangel ein Sicherheitsrisiko darstellt.')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('planned', 'Instandsetzung geplant'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt'), ('verified', 'Nachkontrolliert')], default='open', max_length=30)),
                ('planned_resolution_date', models.DateField(blank=True, null=True)),
                ('public_visible', models.BooleanField(default=False)),
                ('public_note', models.TextField(blank=True, help_text='Optionale zusätzliche öffentliche Erläuterung.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='playgrounds.playequipment')),
            ],
            options={
                'verbose_name': 'Mangel',
                'verbose_name_plural': 'Mängel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('public_visible', models.BooleanField(default=False)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.defect')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_images', to='media_assets.imageasset')),
            ],
            options={
                'verbose_name': 'Mangelbild',
                'verbose_name_plural': 'Mangelbilder',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('visual', 'Visuelle Routinekontrolle'), ('operational', 'Operative Kontrolle'), ('annual', 'Jährliche Hauptinspektion')], max_length=30)),
                ('inspected_at', models.DateField()),
                ('result', models.CharField(choices=[('ok', 'Keine Mängel'), ('defects', 'Mängel festgestellt'), ('restricted', 'Nutzung eingeschränkt'), ('closed', 'Sperrung empfohlen')], default='ok', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playground_inspections', to=settings.AUTH_USER_MODEL)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='playgrounds.playground')),
            ],
            options={
                'verbose_name': 'Kontrolle',
                'verbose_name_plural': 'Kontrollen',
                'ordering': ['-inspected_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspection'),
        ),
        migrations.CreateModel(
            name='InspectionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('inspection_text', models.TextField(blank=True)),
                ('maintenance_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Leer bedeutet: globales Standard-Prüfkriterium.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_criteria', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Prüfkriterium',
                'verbose_name_plural': 'Prüfkriterien',
                'ordering': ['area', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('ok', 'In Ordnung'), ('defect', 'Mangel'), ('not_applicable', 'Nicht anwendbar')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspection')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='inspections.inspectioncriterion')),
            ],
            options={
                'verbose_name': 'Prüfantwort',
                'verbose_name_plural': 'Prüfantworten',
                'ordering': ['criterion__area', 'criterion__title'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30)),
                ('public_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_actions', to='inspections.defect')),
            ],
            options={
                'verbose_name': 'Massnahme',
                'verbose_name_plural': 'Massnahmen',
                'ordering': ['planned_date', 'created_at'],
            },
        ),
    ]
