from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playgrounds", "0001_initial"),
        ("media_assets", "0001_initial"),
        ("tenants", "0002_organization_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionCriterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area", models.CharField(blank=True, max_length=255, verbose_name="Bereich")),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("inspection_text", models.TextField(blank=True, verbose_name="Prüfhinweis")),
                ("maintenance_text", models.TextField(blank=True, verbose_name="Wartungshinweis")),
                ("norm_reference", models.CharField(blank=True, max_length=255, verbose_name="Norm-/Quellenhinweis")),
                ("minimum_inspection_type", models.CharField(choices=[("visual", "Visual routine inspection"), ("operational", "Operational inspection"), ("annual", "Annual main inspection")], default="operational", help_text="Legt fest, ab welcher Kontrollart dieses Prüfkriterium berücksichtigt wird. Visuelle Kriterien erscheinen auch bei operativen und jährlichen Kontrollen.", max_length=30, verbose_name="Mindest-Kontrollart")),
                ("is_standard", models.BooleanField(default=False, verbose_name="Standardkriterium")),
                ("standard_version", models.CharField(blank=True, max_length=100, verbose_name="Standardversion")),
                ("source_note", models.TextField(blank=True, verbose_name="Quellen-/Bearbeitungshinweis")),
                ("is_locked", models.BooleanField(default=False, help_text="Gesperrte globale Standards dürfen durch Organisationen nicht verändert werden.", verbose_name="Gesperrt")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("organization", models.ForeignKey(blank=True, help_text="Leer lassen für globale Anbieter-Standards.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inspection_criteria", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["area", "title"], "verbose_name": "Prüfkriterium", "verbose_name_plural": "Prüfkriterien"},
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inspection_type", models.CharField(choices=[("visual", "Visual routine inspection"), ("operational", "Operational inspection"), ("annual", "Annual main inspection")], default="visual", max_length=30, verbose_name="Kontrollart")),
                ("inspected_at", models.DateField(default=django.utils.timezone.localdate, verbose_name="Kontrolldatum")),
                ("result", models.CharField(choices=[("ok", "OK"), ("defects", "Defects found")], default="ok", max_length=30, verbose_name="Ergebnis")),
                ("status", models.CharField(choices=[("draft", "In progress"), ("completed", "Completed")], default="draft", max_length=30, verbose_name="Status")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgeschlossen am")),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_inspections", to=settings.AUTH_USER_MODEL, verbose_name="Abgeschlossen durch")),
                ("inspector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inspections", to=settings.AUTH_USER_MODEL, verbose_name="Kontrollperson")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspections", to="playgrounds.playground", verbose_name="Spielplatz")),
            ],
            options={"ordering": ["-inspected_at", "-created_at"], "verbose_name": "Kontrolle", "verbose_name_plural": "Kontrollen"},
        ),
        migrations.CreateModel(
            name="InspectionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inspection_type", models.CharField(choices=[("visual", "Visual routine inspection"), ("operational", "Operational inspection"), ("annual", "Annual main inspection")], max_length=30, verbose_name="Kontrollart")),
                ("interval_days", models.PositiveIntegerField(help_text="Intervall für die Kontrollplanung auf Basis von SN EN 1176/1177.", verbose_name="Intervall in Tagen")),
                ("applies_to_all_playgrounds", models.BooleanField(default=True, verbose_name="Gilt für alle Spielplätze")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspection_rules", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["organization__name", "inspection_type"], "verbose_name": "Kontrollregel", "verbose_name_plural": "Kontrollregeln", "unique_together": {("organization", "inspection_type")}},
        ),
        migrations.CreateModel(
            name="InspectionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inspection_type", models.CharField(choices=[("visual", "Visual routine inspection"), ("operational", "Operational inspection"), ("annual", "Annual main inspection")], max_length=30, verbose_name="Kontrollart")),
                ("due_date", models.DateField(verbose_name="Fällig am")),
                ("planned_date", models.DateField(blank=True, null=True, verbose_name="Geplant am")),
                ("status", models.CharField(choices=[("open", "Open"), ("planned", "Planned"), ("completed", "Done"), ("overdue", "Overdue"), ("suspended", "Suspended"), ("cancelled", "Cancelled")], default="open", max_length=30, verbose_name="Status")),
                ("source", models.CharField(choices=[("automatic", "Automatic"), ("manual", "Manual")], default="automatic", max_length=30, verbose_name="Quelle")),
                ("note", models.TextField(blank=True, verbose_name="Interne Notiz")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_inspection_tasks", to=settings.AUTH_USER_MODEL, verbose_name="Zuständige Person")),
                ("completed_by_inspection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_tasks", to="inspections.inspection", verbose_name="Durch Kontrolle abgeschlossen")),
                ("created_from_inspection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_tasks", to="inspections.inspection", verbose_name="Aus Kontrolle erzeugt")),
                ("generated_from_inspection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_tasks", to="inspections.inspection", verbose_name="Aus Kontrolle erzeugt (alt)")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspection_tasks", to="tenants.organization", verbose_name="Organisation")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspection_tasks", to="playgrounds.playground", verbose_name="Spielplatz")),
            ],
            options={"ordering": ["due_date", "playground__name", "inspection_type"], "verbose_name": "Kontrollauftrag", "verbose_name_plural": "Kontrollaufträge", "indexes": [models.Index(fields=["organization", "due_date", "status"], name="inspection_organiz_9f4e2f_idx"), models.Index(fields=["playground", "inspection_type", "due_date"], name="inspection_playgro_f2f99f_idx")]},
        ),
        migrations.CreateModel(
            name="InspectionScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_type", models.CharField(choices=[("playground", "General playground inspection"), ("equipment", "Play equipment"), ("surface", "Impact protection surface / ground"), ("accessory", "Additional equipment")], max_length=30, verbose_name="Prüfbereich")),
                ("label", models.CharField(max_length=255, verbose_name="Bezeichnung")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Sortierung")),
                ("accessory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inspection_scopes", to="playgrounds.playgroundaccessory", verbose_name="Zusatzausstattung")),
                ("equipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inspection_scopes", to="playgrounds.playequipment", verbose_name="Spielgerät")),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scopes", to="inspections.inspection", verbose_name="Kontrolle")),
                ("surface", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inspection_scopes", to="playgrounds.playgroundsurface", verbose_name="Fallschutzfläche / Boden")),
            ],
            options={"ordering": ["sort_order", "label"], "verbose_name": "Prüfbereich", "verbose_name_plural": "Prüfbereiche"},
        ),
        migrations.CreateModel(
            name="InspectionAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.CharField(choices=[("pending", "Not checked yet"), ("ok", "OK"), ("defect", "Defect"), ("not_applicable", "Not applicable")], default="pending", max_length=30, verbose_name="Antwort")),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="answers", to="inspections.inspectioncriterion", verbose_name="Prüfkriterium")),
                ("equipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inspection_answers", to="playgrounds.playequipment", verbose_name="Spielgerät")),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="inspections.inspection", verbose_name="Kontrolle")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="inspections.inspectionscope", verbose_name="Prüfbereich")),
            ],
            options={"ordering": ["scope__sort_order", "criterion__area", "criterion__title"], "verbose_name": "Prüfantwort", "verbose_name_plural": "Prüfantworten", "unique_together": {("inspection", "scope", "criterion")}},
        ),
        migrations.CreateModel(
            name="InspectionCriterionApplicability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_type", models.CharField(choices=[("playground", "General playground inspection"), ("equipment", "Play equipment"), ("surface", "Impact protection surface / ground"), ("accessory", "Additional equipment")], max_length=30, verbose_name="Geltungsbereich")),
                ("applies_to_all_equipment", models.BooleanField(default=False, help_text="Nur relevant, wenn der Geltungsbereich «Spielgerät» ist.", verbose_name="Gilt für alle Spielgerätearten")),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applicabilities", to="inspections.inspectioncriterion", verbose_name="Prüfkriterium")),
                ("equipment_types", models.ManyToManyField(blank=True, help_text="Nur relevant, wenn der Geltungsbereich «Spielgerät» ist und das Prüfkriterium nicht für alle Spielgerätearten gilt.", related_name="criterion_applicabilities", to="playgrounds.equipmenttype", verbose_name="Nur für diese Spielgerätearten")),
            ],
            options={"ordering": ["criterion__area", "criterion__title", "scope_type"], "verbose_name": "Anwendbarkeit", "verbose_name_plural": "Anwendbarkeiten", "unique_together": {("criterion", "scope_type")}},
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("inspection", "Inspection"), ("citizen_report", "Citizen report"), ("internal_report", "Internal report"), ("maintenance", "Maintenance / care"), ("other", "Other")], default="internal_report", max_length=30, verbose_name="Quelle")),
                ("reported_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Gemeldet am")),
                ("reported_by_text", models.CharField(blank=True, help_text="Optionaler Freitext, z. B. Bürgerin, Hauswart, Werkhof.", max_length=255, verbose_name="Gemeldet durch")),
                ("internal_description", models.TextField(verbose_name="Interne Beschreibung")),
                ("internal_note", models.TextField(blank=True, verbose_name="Interne Notiz")),
                ("has_safety_risk", models.BooleanField(default=False, verbose_name="Sicherheitsrisiko")),
                ("urgency", models.CharField(blank=True, choices=[("a_immediate", "A (immediate)"), ("b_medium_term", "B (medium-term)")], help_text="Nur erfassen, wenn ein Sicherheitsrisiko besteht.", max_length=30, verbose_name="Dringlichkeit")),
                ("status", models.CharField(choices=[("open", "Open"), ("planned", "Planned"), ("done", "Resolved"), ("verified", "Checked / completed")], default="open", max_length=30, verbose_name="Status")),
                ("public_visible", models.BooleanField(default=False, verbose_name="Öffentlich sichtbar")),
                ("public_note", models.TextField(blank=True, verbose_name="Öffentlicher Hinweis")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("accessory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects", to="playgrounds.playgroundaccessory", verbose_name="Zusatzausstattung")),
                ("equipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects", to="playgrounds.playequipment", verbose_name="Spielgerät")),
                ("inspection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects", to="inspections.inspection", verbose_name="Kontrolle")),
                ("inspection_answer", models.ForeignKey(blank=True, help_text="Optionale Prüfantwort, aus der dieser Mangel entstanden ist.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects", to="inspections.inspectionanswer", verbose_name="Prüfantwort")),
                ("playground", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="defects", to="playgrounds.playground", verbose_name="Spielplatz")),
                ("surface", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects", to="playgrounds.playgroundsurface", verbose_name="Fallschutzfläche / Boden")),
            ],
            options={"ordering": ["-has_safety_risk", "-created_at"], "verbose_name": "Mangel", "verbose_name_plural": "Mängel"},
        ),
        migrations.CreateModel(
            name="MaintenanceAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("planned_date", models.DateField(blank=True, null=True, verbose_name="Geplant am")),
                ("completed_date", models.DateField(blank=True, null=True, verbose_name="Abgeschlossen am")),
                ("status", models.CharField(choices=[("planned", "Planned"), ("in_progress", "In progress"), ("done", "Completed"), ("cancelled", "Cancelled")], default="planned", max_length=30, verbose_name="Status")),
                ("public_visible", models.BooleanField(default=False, verbose_name="Öffentlich sichtbar")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_maintenance_actions", to=settings.AUTH_USER_MODEL, verbose_name="Zuständige Person")),
                ("defect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_actions", to="inspections.defect", verbose_name="Mangel")),
            ],
            options={"ordering": ["planned_date", "-created_at"], "verbose_name": "Instandhaltungsmassnahme", "verbose_name_plural": "Instandhaltungsmassnahmen"},
        ),
        migrations.CreateModel(
            name="DefectImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("caption", models.CharField(blank=True, max_length=255, verbose_name="Bildlegende")),
                ("public_visible", models.BooleanField(default=False, verbose_name="Öffentlich sichtbar")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("defect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="inspections.defect", verbose_name="Mangel")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="defect_images", to="media_assets.imageasset", verbose_name="Bild")),
            ],
            options={"ordering": ["created_at"], "verbose_name": "Mangelbild", "verbose_name_plural": "Mangelbilder"},
        ),
    ]
