# Generated by ChatGPT on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="inspection_answer",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionale Prüfantwort, aus der dieser Mangel entstanden ist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defects",
                to="inspections.inspectionanswer",
                verbose_name="Prüfantwort",
            ),
        ),
    ]
