# Generated by Django 6.0.5 on 2026-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectioncriterion_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionanswer',
            name='answer',
            field=models.CharField(choices=[('pending', 'Noch nicht geprüft'), ('ok', 'In Ordnung'), ('defect', 'Mangel'), ('not_applicable', 'Nicht anwendbar')], default='pending', max_length=30),
        ),
    ]
