# Generated by Django 6.0.5 on 2026-05-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspectionanswer_answer'),
        ('playgrounds', '0002_equipmenttype_is_locked_equipmenttype_is_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionanswer',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Leer bedeutet: allgemeiner spielplatzbezogener Prüfpunkt.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_answers', to='playgrounds.playequipment'),
        ),
    ]
