# Generated by Django 6.0.5 on 2026-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionanswer_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncriterion',
            name='applies_to_equipment',
            field=models.BooleanField(default=True, help_text='Ja, wenn dieses Kriterium für einzelne Spielgeräte gilt.'),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='applies_to_playground',
            field=models.BooleanField(default=False, help_text='Ja, wenn dieses Kriterium für die allgemeine Spielplatzprüfung gilt.'),
        ),
    ]
