# Generated by Django 6.0.5 on 2026-05-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspectioncriterion_applies_to_equipment_and_more'),
        ('playgrounds', '0002_equipmenttype_is_locked_equipmenttype_is_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('playground', 'Allgemeine Spielplatzprüfung'), ('equipment', 'Spielgerät'), ('surface', 'Fallschutzfläche / Boden'), ('accessory', 'Zusatzausstattung')], max_length=30)),
                ('label', models.CharField(blank=True, help_text='Anzeigetitel des Prüfbereichs, z. B. Allgemeine Spielplatzprüfung oder Doppelschaukel.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playequipment')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Prüfbereich',
                'verbose_name_plural': 'Prüfbereiche',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='inspectionanswer',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Prüfbereich innerhalb der Kontrolle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspectionscope'),
        ),
    ]
