# Generated by Django 6.0.5 on 2026-05-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectionscope_inspectionanswer_scope'),
        ('playgrounds', '0002_equipmenttype_is_locked_equipmenttype_is_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='applies_to_equipment',
            field=models.BooleanField(default=True, help_text='Ja, wenn dieses Kriterium für einzelne Spielgeräte gilt.', verbose_name='Gilt für Spielgeräte'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='applies_to_playground',
            field=models.BooleanField(default=False, help_text='Ja, wenn dieses Kriterium für die allgemeine Spielplatzprüfung gilt.', verbose_name='Gilt für allgemeine Spielplatzprüfung'),
        ),
        migrations.CreateModel(
            name='InspectionCriterionApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('playground', 'Allgemeine Spielplatzprüfung'), ('equipment', 'Spielgerät'), ('surface', 'Fallschutzfläche / Boden'), ('accessory', 'Zusatzausstattung')], max_length=30)),
                ('applies_to_all_equipment', models.BooleanField(default=False, help_text='Nur relevant für Scope-Typ Spielgerät.', verbose_name='Gilt für alle Spielgeräte')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='inspections.inspectioncriterion')),
                ('equipment_types', models.ManyToManyField(blank=True, help_text='Nur relevant für Scope-Typ Spielgerät, wenn nicht für alle Spielgeräte gültig.', related_name='criterion_applicabilities', to='playgrounds.equipmenttype', verbose_name='Gilt für Spielgerätearten')),
            ],
            options={
                'verbose_name': 'Anwendbarkeit Prüfkriterium',
                'verbose_name_plural': 'Anwendbarkeiten Prüfkriterien',
                'ordering': ['criterion__area', 'criterion__title', 'scope_type'],
                'unique_together': {('criterion', 'scope_type')},
            },
        ),
    ]
