# Generated by Django 6.0.5 on 2026-05-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_inspectioncriterion_applies_to_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectioncriterion',
            name='applies_to_equipment',
        ),
        migrations.RemoveField(
            model_name='inspectioncriterion',
            name='applies_to_playground',
        ),
    ]
