# Generated by Django 6.0.5 on 2026-05-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_remove_inspectioncriterion_applies_to_equipment_and_more'),
        ('playgrounds', '0003_playgroundaccessory_playgroundsurface'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionscope',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playgroundaccessory'),
        ),
        migrations.AddField(
            model_name='inspectionscope',
            name='surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playgroundsurface'),
        ),
    ]
