# Generated by Django 6.0.5 on 2026-05-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_inspectionscope_accessory_inspectionscope_surface'),
        ('playgrounds', '0003_playgroundaccessory_playgroundsurface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectioncriterionapplicability',
            options={'ordering': ['criterion__area', 'criterion__title', 'scope_type'], 'verbose_name': 'Anwendbarkeit', 'verbose_name_plural': 'Anwendbarkeiten'},
        ),
        migrations.AlterField(
            model_name='inspectioncriterionapplicability',
            name='applies_to_all_equipment',
            field=models.BooleanField(default=False, help_text='Nur relevant, wenn der Geltungsbereich «Spielgerät» ist.', verbose_name='Gilt für alle Spielgerätearten'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterionapplicability',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='inspections.inspectioncriterion', verbose_name='Prüfkriterium'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterionapplicability',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, help_text='Nur relevant, wenn der Geltungsbereich «Spielgerät» ist und das Prüfkriterium nicht für alle Spielgerätearten gilt.', related_name='criterion_applicabilities', to='playgrounds.equipmenttype', verbose_name='Nur für diese Spielgerätearten'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterionapplicability',
            name='scope_type',
            field=models.CharField(choices=[('playground', 'Allgemeine Spielplatzprüfung'), ('equipment', 'Spielgerät'), ('surface', 'Fallschutzfläche / Boden'), ('accessory', 'Zusatzausstattung')], max_length=30, verbose_name='Geltungsbereich'),
        ),
    ]
