# Generated by Django 6.0.5 on 2026-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_alter_inspectioncriterionapplicability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncriterion',
            name='minimum_inspection_type',
            field=models.CharField(choices=[('visual', 'Visuelle Routinekontrolle'), ('operational', 'Operative Kontrolle'), ('annual', 'Jährliche Hauptinspektion')], default='operational', help_text='Legt fest, ab welcher Kontrollart dieses Prüfkriterium berücksichtigt wird. Visuelle Kriterien erscheinen auch bei operativen und jährlichen Kontrollen.', max_length=30, verbose_name='Mindest-Kontrollart'),
        ),
    ]
