# Generated by Django 6.0.5 on 2026-05-08 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_inspectioncriterion_minimum_inspection_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Abgeschlossen durch'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'In Bearbeitung'), ('completed', 'Abgeschlossen')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
