# Generated by Django 6.0.5 on 2026-05-08 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_inspection_completed_at_inspection_completed_by_and_more'),
        ('media_assets', '0002_initial'),
        ('playgrounds', '0004_playground_photo_alter_playequipment_photo'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['-has_safety_risk', 'planned_resolution_date', '-created_at'], 'verbose_name': 'Mangel', 'verbose_name_plural': 'Mängel'},
        ),
        migrations.AlterModelOptions(
            name='defectimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mangelbild', 'verbose_name_plural': 'Mangelbilder'},
        ),
        migrations.AlterModelOptions(
            name='inspectionanswer',
            options={'ordering': ['scope__sort_order', 'criterion__area', 'criterion__title'], 'verbose_name': 'Prüfantwort', 'verbose_name_plural': 'Prüfantworten'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceaction',
            options={'ordering': ['planned_date', '-created_at'], 'verbose_name': 'Instandhaltungsmassnahme', 'verbose_name_plural': 'Instandhaltungsmassnahmen'},
        ),
        migrations.AddField(
            model_name='defect',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='playgrounds.playgroundaccessory', verbose_name='Zusatzausstattung'),
        ),
        migrations.AddField(
            model_name='defect',
            name='playground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='playgrounds.playground', verbose_name='Spielplatz'),
        ),
        migrations.AddField(
            model_name='defect',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gemeldet am'),
        ),
        migrations.AddField(
            model_name='defect',
            name='reported_by_text',
            field=models.CharField(blank=True, help_text='Optionaler Freitext, z. B. Bürgerin, Hauswart, Werkhof.', max_length=255, verbose_name='Gemeldet durch'),
        ),
        migrations.AddField(
            model_name='defect',
            name='source_type',
            field=models.CharField(choices=[('inspection', 'Kontrolle'), ('citizen_report', 'Bürgermeldung'), ('internal_report', 'Interne Meldung'), ('maintenance', 'Unterhalt / Pflege'), ('other', 'Sonstiges')], default='internal_report', max_length=30, verbose_name='Quelle'),
        ),
        migrations.AddField(
            model_name='defect',
            name='surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='playgrounds.playgroundsurface', verbose_name='Fallschutzfläche / Boden'),
        ),
        migrations.AddField(
            model_name='defect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='defectimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='inspectionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='playgrounds.playequipment', verbose_name='Spielgerät'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='has_safety_risk',
            field=models.BooleanField(default=False, verbose_name='Sicherheitsrisiko'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='inspection',
            field=models.ForeignKey(blank=True, help_text='Optional. Ein Mangel kann aus einer Kontrolle stammen, muss aber nicht.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='inspections.inspection', verbose_name='Kontrolle'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='internal_description',
            field=models.TextField(verbose_name='Interne Beschreibung'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Interne Notiz'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='planned_resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geplante Behebung'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='public_note',
            field=models.TextField(blank=True, verbose_name='Öffentlicher Hinweis'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='public_visible',
            field=models.BooleanField(default=False, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('planned', 'Geplant'), ('done', 'Behoben'), ('verified', 'Geprüft / abgeschlossen')], default='open', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='defectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bildlegende'),
        ),
        migrations.AlterField(
            model_name='defectimage',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.defect', verbose_name='Mangel'),
        ),
        migrations.AlterField(
            model_name='defectimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_images', to='media_assets.imageasset', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='defectimage',
            name='public_visible',
            field=models.BooleanField(default=False, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspected_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Kontrolldatum'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('visual', 'Visuelle Routinekontrolle'), ('operational', 'Operative Kontrolle'), ('annual', 'Jährliche Hauptinspektion')], default='visual', max_length=30, verbose_name='Kontrollart'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Kontrollperson'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='playgrounds.playground', verbose_name='Spielplatz'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='result',
            field=models.CharField(choices=[('ok', 'In Ordnung'), ('defects', 'Mängel festgestellt')], default='ok', max_length=30, verbose_name='Ergebnis'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='answer',
            field=models.CharField(choices=[('pending', 'Noch nicht geprüft'), ('ok', 'In Ordnung'), ('defect', 'Mangel'), ('not_applicable', 'Nicht anwendbar')], default='pending', max_length=30, verbose_name='Antwort'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='inspections.inspectioncriterion', verbose_name='Prüfkriterium'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_answers', to='playgrounds.playequipment', verbose_name='Spielgerät'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspection', verbose_name='Kontrolle'),
        ),
        migrations.AlterField(
            model_name='inspectionanswer',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspectionscope', verbose_name='Prüfbereich'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='inspection_text',
            field=models.TextField(blank=True, verbose_name='Prüfhinweis'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Gesperrte globale Standards dürfen durch Organisationen nicht verändert werden.', verbose_name='Gesperrt'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='is_standard',
            field=models.BooleanField(default=False, verbose_name='Standardkriterium'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='maintenance_text',
            field=models.TextField(blank=True, verbose_name='Wartungshinweis'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='norm_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Norm-/Quellenhinweis'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Leer lassen für globale Anbieter-Standards.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_criteria', to='tenants.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='source_note',
            field=models.TextField(blank=True, verbose_name='Quellen-/Bearbeitungshinweis'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='standard_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Standardversion'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playgroundaccessory', verbose_name='Zusatzausstattung'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playequipment', verbose_name='Spielgerät'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='inspections.inspection', verbose_name='Kontrolle'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='scope_type',
            field=models.CharField(choices=[('playground', 'Allgemeine Spielplatzprüfung'), ('equipment', 'Spielgerät'), ('surface', 'Fallschutzfläche / Boden'), ('accessory', 'Zusatzausstattung')], max_length=30, verbose_name='Prüfbereich'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sortierung'),
        ),
        migrations.AlterField(
            model_name='inspectionscope',
            name='surface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_scopes', to='playgrounds.playgroundsurface', verbose_name='Fallschutzfläche / Boden'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Abgeschlossen am'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_actions', to='inspections.defect', verbose_name='Mangel'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geplant am'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='public_visible',
            field=models.BooleanField(default=False, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('done', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionanswer',
            unique_together={('inspection', 'scope', 'criterion')},
        ),
    ]
