# Generated by Django 6.0.5 on 2026-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_defect_urgency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inspectiontask',
            new_name='inspections_organiz_e42d36_idx',
            old_name='inspection__organiz_3e0302_idx',
        ),
        migrations.RenameIndex(
            model_name='inspectiontask',
            new_name='inspections_playgro_e2492e_idx',
            old_name='inspection__playgro_dfdc60_idx',
        ),
    ]
