# Generated by Django 6.0.5 on 2026-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0019_align_translated_choice_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionrule",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("visual", "Visual routine inspection"),
                    ("operational", "Operational inspection"),
                    ("annual", "Annual main inspection"),
                ],
                max_length=30,
                verbose_name="Kontrollart",
            ),
        ),
    ]
