import uuid

from django.conf import settings
from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media_assets", "0001_initial"),
        ("tenants", "0002_organization_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("code", models.CharField(blank=True, max_length=80, verbose_name="Code")),
                ("norm_reference", models.CharField(blank=True, help_text="Zum Beispiel: SN EN 1176, SN EN 1177 oder gerätespezifische Referenz.", max_length=200, verbose_name="Norm-/Quellenhinweis")),
                ("is_standard", models.BooleanField(default=False, help_text="Ja, wenn dieser Eintrag Teil des globalen App-Standardkatalogs ist.", verbose_name="Standardwert")),
                ("standard_version", models.CharField(blank=True, help_text="Version des Standardkatalogs, z. B. SN-EN-1176-1177-v1.", max_length=80, verbose_name="Standardversion")),
                ("source_note", models.TextField(blank=True, verbose_name="Interner Quellen-/Bearbeitungshinweis")),
                ("is_locked", models.BooleanField(default=False, help_text="Gesperrte Standardwerte können nur durch Super-Admins geändert werden.", verbose_name="Gesperrt")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("organization", models.ForeignKey(blank=True, help_text="Leer bedeutet: globale Standard-Spielgeräteart.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="equipment_types", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["name"], "verbose_name": "Spielgeräteart", "verbose_name_plural": "Spielgerätearten"},
        ),
        migrations.CreateModel(
            name="EquipmentSupplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("tel_nr", models.CharField(blank=True, max_length=80, verbose_name="Telefonnummer")),
                ("strasse", models.CharField(blank=True, max_length=80, verbose_name="Strasse")),
                ("plz_ort", models.CharField(blank=True, max_length=80, verbose_name="PLZ / Ort")),
                ("e_mail", models.EmailField(blank=True, max_length=80, verbose_name="E-Mail")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("organization", models.ForeignKey(blank=True, help_text="Leer bedeutet: global nutzbarer Lieferant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="equipment_suppliers", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["name"], "verbose_name": "Lieferant", "verbose_name_plural": "Lieferanten", "unique_together": {("organization", "name")}},
        ),
        migrations.CreateModel(
            name="Playground",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="Eindeutige UUID des Spielplatzes. Beim Webservice-Abgleich wird darüber synchronisiert.", unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(max_length=100, verbose_name="URL-Kürzel")),
                ("number", models.IntegerField(blank=True, null=True, verbose_name="Nummer")),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="Adresse")),
                ("street_name", models.CharField(blank=True, max_length=200, verbose_name="Strassenname")),
                ("house_number", models.CharField(blank=True, max_length=40, verbose_name="Hausnummer")),
                ("district", models.CharField(blank=True, max_length=100, verbose_name="Quartier")),
                ("latitude", models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name="LV95 Y")),
                ("longitude", models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name="LV95 X")),
                ("location", django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Aus LV95 X/Y abgeleiteter Punkt für räumliche Abfragen mit SpatiaLite.", null=True, srid=2056, verbose_name="Lagegeometrie")),
                ("description", models.TextField(blank=True, verbose_name="Beschrieb")),
                ("construction_costs", models.FloatField(blank=True, null=True, verbose_name="Erstellungskosten")),
                ("inspection_suspended_from", models.DateField(blank=True, null=True, verbose_name="Inspektion aussetzen von")),
                ("inspection_suspended_until", models.DateField(blank=True, null=True, verbose_name="Inspektion aussetzen bis")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("public_visible", models.BooleanField(default=True, verbose_name="Öffentlich")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("default_annual_inspector", models.ForeignKey(blank=True, help_text="Wird bei neuen jährlichen Kontrollaufträgen automatisch voreingestellt.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_annual_playgrounds", to=settings.AUTH_USER_MODEL, verbose_name="Default-Kontrolleur/in jährlich")),
                ("default_operational_inspector", models.ForeignKey(blank=True, help_text="Wird bei neuen operativen Kontrollaufträgen automatisch voreingestellt.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_operational_playgrounds", to=settings.AUTH_USER_MODEL, verbose_name="Default-Kontrolleur/in operativ")),
                ("default_visual_inspector", models.ForeignKey(blank=True, help_text="Wird bei neuen visuellen Kontrollaufträgen automatisch voreingestellt.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_visual_playgrounds", to=settings.AUTH_USER_MODEL, verbose_name="Default-Kontrolleur/in visuell")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="playgrounds", to="tenants.organization", verbose_name="Organisation")),
                ("photo", models.ForeignKey(blank=True, help_text="Optionales Hauptfoto des Spielplatzes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="playgrounds", to="media_assets.imageasset", verbose_name="Foto")),
            ],
            options={"ordering": ["organization__name", "name"], "verbose_name": "Spielplatz", "verbose_name_plural": "Spielplätze", "unique_together": {("organization", "slug")}},
        ),
        migrations.CreateModel(
            name="PlayEquipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("sequence_number", models.PositiveIntegerField(blank=True, null=True, verbose_name="Laufnummer")),
                ("inventory_number", models.CharField(blank=True, max_length=100, verbose_name="Inventar-Nr.")),
                ("norm", models.CharField(blank=True, max_length=200, verbose_name="Norm")),
                ("year_built", models.DateField(blank=True, null=True, verbose_name="Baujahr / Baudatum")),
                ("build_date", models.DateField(blank=True, null=True, verbose_name="Baudatum")),
                ("demolition_date", models.DateField(blank=True, null=True, verbose_name="Abbruchjahr / Abbruchdatum")),
                ("renovation_type", models.CharField(blank=True, choices=[("total", "Totalsanierung"), ("partial", "Teilsanierung")], max_length=20, verbose_name="Sanierungsart")),
                ("recommended_renovation_year", models.PositiveIntegerField(blank=True, help_text="Vierstellige Jahreszahl. Historische Legacy-Werte sind zulässig.", null=True, verbose_name="Empfohlenes Sanierungsjahr")),
                ("renovation_comment", models.CharField(blank=True, max_length=500, verbose_name="Kommentar zur Sanierung")),
                ("not_to_inspect", models.BooleanField(default=False, help_text="Administrative Prüfausnahme. Das Spielgerät bleibt im Bestand, wird aber nicht in Kontrollprotokollen berücksichtigt. Dieses Feld wird durch die Organisation verwaltet.", verbose_name="Nicht zu prüfen")),
                ("not_to_inspect_reason", models.CharField(blank=True, max_length=500, verbose_name="Grund nicht zu prüfen")),
                ("not_inspectable", models.BooleanField(default=False, help_text="Das Spielgerät muss grundsätzlich geprüft werden, konnte aber bei einer Kontrolle nicht geprüft werden, z. B. weil es nicht zugänglich war.", verbose_name="Nicht prüfbar")),
                ("not_inspectable_reason", models.CharField(blank=True, max_length=500, verbose_name="Grund nicht prüfbar")),
                ("latitude", models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name="LV95 Y")),
                ("longitude", models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name="LV95 X")),
                ("location", django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Aus LV95 X/Y abgeleiteter Punkt für räumliche Abfragen mit SpatiaLite.", null=True, srid=2056, verbose_name="Lagegeometrie")),
                ("public_visible", models.BooleanField(default=True, verbose_name="Öffentlich sichtbar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("equipment_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment", to="playgrounds.equipmenttype", verbose_name="Spielgeräteart")),
                ("photo", models.ForeignKey(blank=True, help_text="Optionales Hauptfoto dieses Spielgeräts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="play_equipment", to="media_assets.imageasset", verbose_name="Foto")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to="playgrounds.playground", verbose_name="Spielplatz")),
                ("supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipment", to="playgrounds.equipmentsupplier", verbose_name="Lieferant")),
            ],
            options={"ordering": ["playground__name", "sequence_number", "name"], "verbose_name": "Spielgerät", "verbose_name_plural": "Spielgeräte"},
        ),
        migrations.CreateModel(
            name="PlaygroundSurface",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("surface_type", models.CharField(choices=[("sand", "Sand"), ("gravel", "Rundkies / Fallschutzkies"), ("wood_chips", "Holzschnitzel"), ("bark", "Rindenmulch"), ("rubber", "Fallschutzbelag"), ("grass", "Rasen"), ("other", "Sonstiger Belag")], default="other", max_length=50, verbose_name="Belagsart")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("public_visible", models.BooleanField(default=True, verbose_name="Öffentlich sichtbar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="surfaces", to="playgrounds.playground", verbose_name="Spielplatz")),
            ],
            options={"ordering": ["playground__name", "name"], "verbose_name": "Fallschutzfläche / Boden", "verbose_name_plural": "Fallschutzflächen / Böden"},
        ),
        migrations.CreateModel(
            name="PlaygroundAccessory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("accessory_type", models.CharField(choices=[("bench", "Sitzbank"), ("waste_bin", "Abfalleimer"), ("fence", "Zaun"), ("gate", "Tor"), ("sign", "Beschilderung"), ("lighting", "Beleuchtung"), ("table", "Tisch"), ("shade", "Sonnenschutz"), ("other", "Sonstige Ausstattung")], default="other", max_length=50, verbose_name="Ausstattungsart")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("public_visible", models.BooleanField(default=True, verbose_name="Öffentlich sichtbar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accessories", to="playgrounds.playground", verbose_name="Spielplatz")),
            ],
            options={"ordering": ["playground__name", "name"], "verbose_name": "Zusatzausstattung", "verbose_name_plural": "Zusatzausstattung"},
        ),
        migrations.CreateModel(
            name="PlaygroundDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(choices=[("certificate", "Zertifikatsdokument"), ("acceptance", "Abnahmedokument")], max_length=20, verbose_name="Dokumentart")),
                ("mime_type", models.CharField(default="application/pdf", max_length=100, verbose_name="MIME-Type")),
                ("size_bytes", models.PositiveIntegerField(verbose_name="Dateigrösse in Bytes")),
                ("sha256", models.CharField(db_index=True, max_length=64, verbose_name="SHA-256")),
                ("data", models.BinaryField(verbose_name="Dateidaten")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("playground", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="playgrounds.playground", verbose_name="Spielplatz")),
            ],
            options={"ordering": ["document_type", "id"], "verbose_name": "Spielplatz-Dokument", "verbose_name_plural": "Spielplatz-Dokumente"},
        ),
        migrations.CreateModel(
            name="Quartier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Quartiername")),
                ("geom", models.JSONField(help_text="Importierte GeoJSON-Geometrie des Quartiers. Erwartet Polygon oder MultiPolygon in LV95-Koordinaten.", verbose_name="GeoJSON-Geometrie")),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text="Aus GeoJSON abgeleitete MultiPolygon-Geometrie für räumliche Abfragen mit SpatiaLite.", null=True, srid=2056, verbose_name="Geometrie")),
                ("source", models.CharField(blank=True, max_length=500, verbose_name="Quelle")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("imported_at", models.DateTimeField(auto_now=True, verbose_name="Importiert am")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quartiere", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["organization__name", "name"], "verbose_name": "Quartier", "verbose_name_plural": "Quartiere", "unique_together": {("organization", "name")}},
        ),
        migrations.CreateModel(
            name="QuartierImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geojson_file", models.FileField(blank=True, help_text="Optional. Erwartet FeatureCollection mit Quartiername und Geometrie/geom.", upload_to="quartier_imports/", verbose_name="GeoJSON-Datei")),
                ("wfs_endpoint", models.URLField(blank=True, help_text="Optional. Zum Beispiel ein GetCapabilities-Endpoint eines WFS.", max_length=1000, verbose_name="WFS-Endpoint")),
                ("replace_existing", models.BooleanField(default=False, verbose_name="Bestehende Quartiere dieser Organisation vor Import deaktivieren")),
                ("last_import_message", models.TextField(blank=True, verbose_name="Letzte Importmeldung")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quartier_imports", to="tenants.organization", verbose_name="Organisation")),
            ],
            options={"ordering": ["-updated_at"], "verbose_name": "Quartier-Import", "verbose_name_plural": "Quartier-Importe"},
        ),
    ]
