# Generated by Django 6.0.5 on 2026-05-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('norm_reference', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Leer bedeutet: globaler Standard-Gerätetyp.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Spielgeräteart',
                'verbose_name_plural': 'Spielgerätearten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('public_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playgrounds', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Spielplatz',
                'verbose_name_plural': 'Spielplätze',
                'ordering': ['organization__name', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PlayEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inventory_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('public_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='playgrounds.equipmenttype')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_photos', to='media_assets.imageasset')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='playgrounds.playground')),
            ],
            options={
                'verbose_name': 'Spielgerät',
                'verbose_name_plural': 'Spielgeräte',
                'ordering': ['playground__name', 'name'],
            },
        ),
    ]
