# Generated by Django 6.0.5 on 2026-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Gesperrte Standardwerte können nur durch Super-Admins geändert werden.'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Ja, wenn dieser Eintrag Teil des globalen App-Standardkatalogs ist.'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='source_note',
            field=models.TextField(blank=True, help_text='Interner Hinweis zur Quelle oder fachlichen Herleitung.'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='standard_version',
            field=models.CharField(blank=True, help_text='Version des Standardkatalogs, z. B. SN-EN-1176-1177-v1.', max_length=80),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='norm_reference',
            field=models.CharField(blank=True, help_text='Zum Beispiel: SN EN 1176, SN EN 1177 oder gerätespezifische Referenz.', max_length=200),
        ),
    ]
