# Generated by Django 6.0.5 on 2026-05-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0002_equipmenttype_is_locked_equipmenttype_is_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accessory_type', models.CharField(choices=[('bench', 'Sitzbank'), ('waste_bin', 'Abfalleimer'), ('fence', 'Zaun'), ('gate', 'Tor'), ('sign', 'Beschilderung'), ('lighting', 'Beleuchtung'), ('table', 'Tisch'), ('shade', 'Sonnenschutz'), ('other', 'Sonstige Ausstattung')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('public_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='playgrounds.playground')),
            ],
            options={
                'verbose_name': 'Zusatzausstattung',
                'verbose_name_plural': 'Zusatzausstattung',
                'ordering': ['playground__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surface_type', models.CharField(choices=[('sand', 'Sand'), ('gravel', 'Rundkies / Fallschutzkies'), ('wood_chips', 'Holzschnitzel'), ('bark', 'Rindenmulch'), ('rubber', 'Fallschutzbelag'), ('grass', 'Rasen'), ('other', 'Sonstiger Belag')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('public_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='playgrounds.playground')),
            ],
            options={
                'verbose_name': 'Fallschutzfläche / Boden',
                'verbose_name_plural': 'Fallschutzflächen / Böden',
                'ordering': ['playground__name', 'name'],
            },
        ),
    ]
