# Generated by Django 6.0.5 on 2026-05-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_initial'),
        ('playgrounds', '0003_playgroundaccessory_playgroundsurface'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Optionales Hauptfoto des Spielplatzes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playgrounds', to='media_assets.imageasset', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='playequipment',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Optionales Hauptfoto dieses Spielgeräts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_equipment', to='media_assets.imageasset', verbose_name='Foto'),
        ),
    ]
