# Generated by Django 6.0.5 on 2026-05-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0009_playground_document'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playequipment',
            options={'ordering': ['playground__name', 'sequence_number', 'name'], 'verbose_name': 'Spielgerät', 'verbose_name_plural': 'Spielgeräte'},
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Gesperrte Standardwerte können nur durch Super-Admins geändert werden.', verbose_name='Gesperrt'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Ja, wenn dieser Eintrag Teil des globalen App-Standardkatalogs ist.', verbose_name='Standardwert'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='norm_reference',
            field=models.CharField(blank=True, help_text='Zum Beispiel: SN EN 1176, SN EN 1177 oder gerätespezifische Referenz.', max_length=200, verbose_name='Norm-/Quellenhinweis'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Leer bedeutet: globale Standard-Spielgeräteart.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='tenants.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='source_note',
            field=models.TextField(blank=True, verbose_name='Interner Quellen-/Bearbeitungshinweis'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='standard_version',
            field=models.CharField(blank=True, help_text='Version des Standardkatalogs, z. B. SN-EN-1176-1177-v1.', max_length=80, verbose_name='Standardversion'),
        ),
        migrations.AlterField(
            model_name='playequipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='playequipment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='playequipment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playgrounds', to='tenants.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL-Kürzel'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='accessory_type',
            field=models.CharField(choices=[('bench', 'Sitzbank'), ('waste_bin', 'Abfalleimer'), ('fence', 'Zaun'), ('gate', 'Tor'), ('sign', 'Beschilderung'), ('lighting', 'Beleuchtung'), ('table', 'Tisch'), ('shade', 'Sonnenschutz'), ('other', 'Sonstige Ausstattung')], default='other', max_length=50, verbose_name='Ausstattungsart'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='playgrounds.playground', verbose_name='Spielplatz'),
        ),
        migrations.AlterField(
            model_name='playgroundaccessory',
            name='public_visible',
            field=models.BooleanField(default=True, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='playgrounds.playground', verbose_name='Spielplatz'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='public_visible',
            field=models.BooleanField(default=True, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AlterField(
            model_name='playgroundsurface',
            name='surface_type',
            field=models.CharField(choices=[('sand', 'Sand'), ('gravel', 'Rundkies / Fallschutzkies'), ('wood_chips', 'Holzschnitzel'), ('bark', 'Rindenmulch'), ('rubber', 'Fallschutzbelag'), ('grass', 'Rasen'), ('other', 'Sonstiger Belag')], default='other', max_length=50, verbose_name='Belagsart'),
        ),
    ]
